# Copyright (c) 2019-present, The Johann Authors. All Rights Reserved.
# Use of this source code is governed by a BSD-3-clause license that can
# be found in the LICENSE file. See the AUTHORS file for names of contributors.

default:
  image: python:3.6
  tags:
    - docker
  before_script:
    - python3 -V
    - make dev-setup
    - source ./venv/bin/activate

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  PYTHONPATH: "${CI_PROJECT_DIR}"

stages:
  - lint
  - test

.lint:
  stage: lint
  allow_failure: true

lint:
  extends: .lint
  script: make lint
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .cache/pip
      - .cache/pre-commit
      - venv/

safety:
  extends: .lint
  script: make safety
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .cache/pip
      - venv/

.docker:
  variables:
    JOHANN_CORE_ROOT: .
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_TLS_CERTDIR: "/certs"
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - apk add bash

test:
  stage: test
  extends: .docker
  script: make test

clean:
  stage: .post
  when: always
  extends: .docker
  script: make clean
