# Copyright (c) 2019-present, The Johann Authors. All Rights Reserved.
# Use of this source code is governed by a BSD-3-clause license that can
# be found in the LICENSE file. See the AUTHORS file for names of contributors.

default_stages: [commit]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-added-large-files
      - id: detect-private-key
      - id: mixed-line-ending
      - id: name-tests-test
      # PLANNED: - id: check-json
      - id: check-yaml
        # PLANNED: exclude: tests/scores/malformed

  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        # PLANNED: exclude: tests/scores/malformed

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [--config=setup.cfg]
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/jazzband/pip-tools
    rev: 5.2.1
    hooks:
      - id: pip-compile
        args: [--quiet, --generate-hashes, --no-emit-index-url]
        files: ^((requirements(-.*)?\.(in|txt))|setup.py)$
      - id: pip-compile
        name: pip-compile-dev
        args:
          [
            --quiet,
            --allow-unsafe,
            --generate-hashes,
            --no-emit-index-url,
            --output-file=requirements-dev.txt,
            requirements-dev.in,
          ]
        files: ^((requirements(-.*)?\.(in|txt))|setup.py)$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        entry: bandit -lll
        exclude: tests

  - repo: https://github.com/PyCQA/pylint
    rev: master
    hooks:
      - id: pylint
        stages: [manual] # PLANNED: [commit]

  - repo: local
    hooks:
      - id: check-todo
        name: check-todo
        language: pygrep
        entry: (TODO|FIXME|FOOBAR|LEFT OFF HERE)
        args: [-i]
        exclude: .pre-commit-config.yaml
        stages: [push]
      - id: check-copyright-headers
        name: check-copyright-headers
        language: script
        entry: scripts/check_copyright_headers.py
        files: '.*\.py'
      - id: mypy-local
        name: mypy-local
        entry: mypy
        language: system
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        stages: [manual] # PLANNED: [commit]
